### ISSUE TITLE
Latest fix for conf.d directory not released

### ISSUE THREAD

**Issue by jkugler** [jsirex/collectd-lib-cookbook#2]
The version needs to be bumped, and the latest fixes pushed. https://github.com/jsirex/collectd-lib-cookbook/commit/fe856644dd8fe4e89f53e382287922c1c885369a#diff-25e5d4a4446ae12a0d6f1162b6160375 fixed the conf.d name typo, but 3.0.1 that is in the supermarket still has the typo.

**Comment by jsirex** [comment]
Released 3.0.2
